# Generated by Django 2.0.4 on 2018-06-10 11:45

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True,
                                       default=datetime.datetime(2018, 6, 10, 11, 45, 15, 612919, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='track',
            field=models.CharField(
                choices=[('Elektro', 'Elektrotechnik'), ('Info', 'Informatik'), ('Wi-info', 'Wirtschaftsinformatik'),
                         ('T-Info', 'Theoretische Inforamtik')], default='Info', max_length=25),
        ),
    ]
